#file: noinspection YAMLSchemaValidation
name: $name
version: $version
description: $description
author: $author
contributors: [ $contributors ]
website: $website

main: com.minersstudios.whomine.WhoMineImpl
loader: com.minersstudios.whomine.WhoMineLoader
api-version: $apiVersion
dependencies:
  - name: AuthMe
    version: $authMeVersion
  - name: CoreProtect
    version: $coreProtectVersion
load-after:
  - name: AuthMe
  - name: CoreProtect
