name: Unit test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run the test script
      needs: build
      run: sh .github/scripts/test.sh
